Upgrade postgres to 11.16 to match heroku production version (#2984)
Just changing the version led to this error
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

This PR uses trust for postgres instead of a password.

According to the documentation, this should be safe due to

`trust authentication is appropriate and very convenient for local connections on a single-user workstation`

as well as

`This method should only be used when there is adequate operating-system-level protection on connections to the server.`