Upgrade to rails 7 (try again after slug size increase) (#3448)
* Update rails gem from 6.1.7 to 7.0.4

* Silence net-http warnings by adding to Gemfile

Fix these warnings
```
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
```

Recommended by https://github.com/ruby/net-imap/issues/16

* Force uri version to 0.10.0 (default version in Ruby 2.7)

This is to fix these errors until bank gets upgraded to Ruby 3.0

Gem::LoadError: You have already activated uri 0.10.0, but your Gemfile requires uri 0.11.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem.

* Update maildown gem

Fixes this error happening since Rails 7
```
NameError:
 undefined method `extract_handler_and_format_and_variant' for class `ActionView::OptimizedFileSystemResolver'
 /bundle/ruby/2.7.0/gems/maildown-3.3.0/lib/maildown/ext/action_view.rb:7:in `<class:OptimizedFileSystemResolver>'
```

issues and PR on maildown gem repo

https://github.com/zombocom/maildown/issues/65
https://github.com/zombocom/maildown/issues/59
https://github.com/zombocom/maildown/pull/61

* Remove spring dependency

Rails 7 requires at least spring 3.0, but also the belief is that spring
is no longer needed with modern hardware.

From https://rubyonrails.org/2021/12/15/Rails-7-fulfilling-a-vision

```
Spring is no longer on by default, as faster computers have made it less relevant on anything but the largest applications.
```

* Ran bin/rails app:update

- Remove spring preloaders
- When app:update generated files differed from current main, I
  generally favored intentional changes like sendgrid config, but when
  the diffs were mostly commented defaults, I kept the new defaults.
- Rails 7 includes versioned schema.rb dump

* Run ActiveStorage migration added by bin/rails app:update

* Remove lab_tech because it's not compatible with rails 7