Bump rails from 7.2.1.1 to 7.2.2 (#8388)
Bumps [rails](https://github.com/rails/rails) from 7.2.1.1 to 7.2.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">rails's
releases</a>.</em></p>
<blockquote>
<h2>7.2.2</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Include options when instrumenting
<code>ActiveSupport::Cache::Store#delete</code> and
<code>ActiveSupport::Cache::Store#delete_multi</code>.</p>
<p><em>Adam Renberg Tamm</em></p>
</li>
<li>
<p>Print test names when running <code>rails test -v</code> for parallel
tests.</p>
<p><em>John Hawthorn</em>, <em>Abeid Ahmed</em></p>
</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>
<p>Fix regression in <code>alias_attribute</code> to work with user
defined methods.</p>
<p><code>alias_attribute</code> would wrongly assume the attribute
accessor was generated by Active Model.</p>
<pre lang="ruby"><code>class Person
  include ActiveModel::AttributeMethods
<p>define_attribute_methods :name
attr_accessor :name</p>
<p>alias_attribute :full_name, :name
end</p>
<p>person.full_name # =&gt; NoMethodError: undefined method `attribute'
for an instance of Person
</code></pre></p>
<p><em>Jean Boussier</em></p>
</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Fix support for <code>query_cache: false</code> in
<code>database.yml</code>.</p>
<p><code>query_cache: false</code> would no longer entirely disable the
Active Record query cache.</p>
<p><em>zzak</em></p>
</li>
<li>
<p>Set <code>.attributes_for_inspect</code> to <code>:all</code> by
default.</p>
<p>For new applications it is set to <code>[:id]</code> in
config/environment/production.rb.</p>
<p>In the console all the attributes are always shown.</p>
<p><em>Andrew Novoselac</em></p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/d0dcb8fa6073a0c4d42600c15e82e3bb386b27d3"><code>d0dcb8f</code></a>
Preparing for 7.2.2 release</li>
<li><a
href="https://github.com/rails/rails/commit/9f24f753541384d8d63d9a2f25bc4c8bae429bb6"><code>9f24f75</code></a>
Add yarn.lock allowed dirty files</li>
<li><a
href="https://github.com/rails/rails/commit/ad485aaf0e742b803f7aa8416c82138adcc3acd4"><code>ad485aa</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52951">#52951</a>
from Ridhwana/Ridhwana/active-record-validations [c...</li>
<li><a
href="https://github.com/rails/rails/commit/f6916e7d863cb53f8738265f4b5b4629990e84f0"><code>f6916e7</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53494">#53494</a>
from zzak/re-53492</li>
<li><a
href="https://github.com/rails/rails/commit/a7858b54505698d40e12cba56e3c2702ebdadfd8"><code>a7858b5</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53472">#53472</a>
from p8/activerecord/improve-attributes-for-inspect...</li>
<li><a
href="https://github.com/rails/rails/commit/e6a8acd749f0824cbd180014482f3d2dd4bf976c"><code>e6a8acd</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53475">#53475</a>
from p8/activerecord/show-all-attributes-in-console</li>
<li><a
href="https://github.com/rails/rails/commit/91aac4a9348fcf6568a9a2a724c587f524d940b1"><code>91aac4a</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53484">#53484</a>
from zzak/query_cache-config-disable</li>
<li><a
href="https://github.com/rails/rails/commit/fe5f624c3a93ed5adc873e9181d2e6b6babf4460"><code>fe5f624</code></a>
Better wording for config.action_dispatch.show_exceptions [ci-skip] (<a
href="https://redirect.github.com/rails/rails/issues/53483">#53483</a>)</li>
<li><a
href="https://github.com/rails/rails/commit/15872b4e33cd9a60db0a9576146437118b5904c4"><code>15872b4</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53473">#53473</a>
from p8/activerecord/update-attributes-for-inspect-...</li>
<li><a
href="https://github.com/rails/rails/commit/e1cccdcb155f17623118ca1df11065323c2c63c0"><code>e1cccdc</code></a>
Add CHANGELOG entry for 170e6c178b7358a87a7304bdf80273e0b153f6fd</li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v7.2.1.1...v7.2.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=rails&package-manager=bundler&previous-version=7.2.1.1&new-version=7.2.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
Dependabot will merge this PR once CI passes on it, as requested by
@garyhtou.

[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Gary Tou <gary@garytou.com>